import HospitalLayout from "../layouts/HospitalLayout";

const HospitalDashboard = () => {

    const stats = [
        {
            title: "Total Doctors",
            value: "128",
            color: "from-cyan-500 to-blue-700",
        },
        {
            title: "Total Patients",
            value: "5,842",
            color: "from-emerald-500 to-green-700",
        },
        {
            title: "Appointments",
            value: "342",
            color: "from-purple-500 to-indigo-700",
        },
        {
            title: "Revenue",
            value: "$128K",
            color: "from-pink-500 to-rose-700",
        },
    ];

    return (

        <HospitalLayout>

            {/* Header */}

            <div className="mb-10">

                <h1 className="text-6xl font-black text-slate-900">

                    Hospital Dashboard

                </h1>

                <p className="text-gray-500 mt-3 text-lg">

                    Complete overview of your hospital operations.

                </p>

            </div>

            {/* Stats */}

            <div className="grid lg:grid-cols-4 gap-8 mb-10">

                {stats.map((item, index) => (

                    <div
                        key={index}
                        className={`relative overflow-hidden rounded-[36px] bg-gradient-to-r ${item.color} text-white p-8 shadow-2xl hover:-translate-y-2 transition-all duration-500`}
                    >

                        <div className="absolute top-[-40px] right-[-40px] w-[160px] h-[160px] bg-white/10 rounded-full blur-3xl"></div>

                        <p className="text-white/80 text-lg">

                            {item.title}

                        </p>

                        <h2 className="text-6xl font-black mt-5">

                            {item.value}

                        </h2>

                    </div>

                ))}

            </div>

            {/* Main Section */}

            <div className="grid lg:grid-cols-2 gap-8">

                {/* Activity */}

                <div className="bg-white rounded-[36px] p-8 shadow-xl">

                    <h2 className="text-3xl font-black text-slate-900">

                        Recent Activity

                    </h2>

                    <div className="mt-8 space-y-5">

                        <div className="flex items-center gap-4">

                            <div className="w-4 h-4 rounded-full bg-green-500"></div>

                            <p>
                                New patient registered successfully
                            </p>

                        </div>

                        <div className="flex items-center gap-4">

                            <div className="w-4 h-4 rounded-full bg-cyan-500"></div>

                            <p>
                                Prescription generated by Dr. Sharma
                            </p>

                        </div>

                        <div className="flex items-center gap-4">

                            <div className="w-4 h-4 rounded-full bg-purple-500"></div>

                            <p>
                                Appointment approved
                            </p>

                        </div>

                        <div className="flex items-center gap-4">

                            <div className="w-4 h-4 rounded-full bg-pink-500"></div>

                            <p>
                                Revenue report generated
                            </p>

                        </div>

                    </div>

                </div>

                {/* Performance */}

                <div className="relative overflow-hidden rounded-[36px] bg-gradient-to-br from-slate-900 via-blue-950 to-cyan-900 p-8 text-white shadow-2xl">

                    <div className="absolute top-[-50px] right-[-50px] w-[220px] h-[220px] bg-cyan-500/10 rounded-full blur-3xl"></div>

                    <h2 className="text-4xl font-black">

                        Hospital Performance

                    </h2>

                    <p className="mt-4 text-cyan-100">

                        Overall healthcare operations status.

                    </p>

                    <div className="mt-10">

                        <div className="flex justify-between mb-3">

                            <span>Efficiency</span>

                            <span>92%</span>

                        </div>

                        <div className="w-full h-4 bg-white/10 rounded-full">

                            <div className="w-[92%] h-full bg-cyan-400 rounded-full"></div>

                        </div>

                    </div>

                    <div className="mt-8">

                        <div className="flex justify-between mb-3">

                            <span>Patient Satisfaction</span>

                            <span>96%</span>

                        </div>

                        <div className="w-full h-4 bg-white/10 rounded-full">

                            <div className="w-[96%] h-full bg-green-400 rounded-full"></div>

                        </div>

                    </div>

                </div>

            </div>

        </HospitalLayout>

    );

};

export default HospitalDashboard;